AllCops:
  TargetRubyVersion: 2.5

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/Encoding:
  Enabled: false
  
Style/StringLiteralsInInterpolation:
  Enabled: false
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
